### ISSUE TITLE
Server and client synchronization

### ISSUE THREAD

**Issue by EvanGyori** [apples/ginseng#28]
A couple questions I have been struggling with.

How would you go about keeping track of the entities between client and server, so that the server can send a packet and the client would know which entity to change.

What would be the best way for keeping track of the components that have been changed since the last time the client has been updated so I only send the necessary components. I was thinking I could have bools that get set to true on change in every component and loop through every entity and component constantly to see if it needs to update the client but that way seems slow.

Thank you in advance

**Comment by apples** [comment]
I believe keeping a bool flag in each component is probably the best way to handle this right now. It's not as inefficient as you might think.

If you have a visit call like this:
```cpp
entities.visit([](ginseng::database::ent_id eid, PositionComponent& position){
    if (position.hasChanged) {
        send_net_message_to(eid, position);
        position.hasChanged = false;
    }
});
```
This should be very fast.

You just need to ensure that the `hasChanged` flag actually gets set properly.

**Comment by EvanGyori** [comment]
awesome, thanks for the quick response!

as for keeping the server and client's databases alike, am I able to create an entity at a specific index or would it be better to store the server's eid inside a component

**Comment by apples** [comment]
Unfortunately there's no way to create an entity with a specific index.

My suggestion is to assign your own unique id (as a component) to each entity that the server creates, and synchronize based on that. Each side could keep track of the ids with a `std::unordered_map<server_entity_id, ginseng::database::ent_id>` or similar mapping table.

For what it's worth, this technique is pretty much how Unreal Engine synchronizes entities.
