### ISSUE TITLE
Multithreading used for systems?

### ISSUE THREAD

**Issue by tree786** [apples/ginseng#29]
hi

just discovered this framework some hours ago, and was wondering , are systems executed concurrently in ginseng? 

thanks

**Comment by apples** [comment]
Hi there!

Systems are not executed concurrently. If you meant "parallel", then the systems are also not parallel.

The reason in both cases is that the extra overhead of making it work would be significant.

It is usually better to write your own concurrency or threading system which wraps each system, if that's something you need.

Did you have a specific use case in mind?

**Comment by tree786** [comment]
Hi, much thanks for the reply. Ok I see, i didn't have much in mind, but i've used an ECS before that had 'outer-parallelism' which executes systems in parallel, so was wondering how ginseng handles this 
Thanks again
