### ISSUE TITLE
How to surpress warning when using gcc compiler flags?

### ISSUE THREAD

**Issue by tree786** [apples/ginseng#32]
Hi

This questions is not really related to ginseng. But since I am using ginseng in a project I am working on, thought I might get a useful answer. Basically I am compiling my project using several c++ compiler flags (like `-Wall` , `-Wextra` etc), but I am getting huge warning logs which point to ginseng, like this:
```
include/ginseng/ginseng.hpp:620:38: warning: comparison of integer expressions of different signedness: ‘const value_type’ {aka ‘const long unsigned int’} and ‘int’ [-Wsign-compare]

```
I'd like to surpress this `ginseng` specific messgaes, and just display warnings for my own code, but I don't know how. Here is my mock cmake lists file FYI:
```
cmake_minimum_required(VERSION 3.11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_BUILD_TYPE "Release")

project(test)

include_directories("extern/libs/ginseng") #add ginseng.h header

add_executable(binary my_source_file1.cpp
			my_source_file2.cpp
			my_source_file3.cpp
			my_source_file4.cpp
)

target_compile_options(binary PRIVATE
				-Wall 
                                -Wextra
)

target_link_libraries(binary)
```
Do you happen to know what changes I should make to my cmake file to achieve this?

Thanks

**Comment by apples** [comment]
Howdy!

Normally, for `.cpp` files, you can use:
```
set_source_files_properties(my_source_file1.cpp PROPERTIES COMPILE_FLAGS -Wno-sign-compare)
```

But since this will turn the warning off for your own code as well, it is not the best solution.

Unfortunately, since Ginseng is a header-only library, this is unavoidable.

I will work on fixing these warnings in Ginseng.

**Comment by tree786** [comment]
Ok I didn't know about `set_source_files_properties`. No problem, thanks for the info!

**Comment by apples** [comment]
I believe I have fixed all the warnings with `-Wall -Wextra -pedantic` turned on.

Please update and test if you get a chance.

**Comment by tree786** [comment]
Ok, I have just compiled it, but I'm getting quite a few `-Wunused-variable` warnings, like this:

```
include/ginseng/ginseng.hpp:390:17: warning: unused variable ‘i’ [-Wunused-variable]
```

**Comment by apples** [comment]
I've found the issue. It was a problem with the testing framework of all things...

There **shouldn't** be any more warnings. If there are, please provide some test code that reproduces the warning, and what compiler version and flags you're using.

Because Ginseng uses a lot of templates, it's possible that there are some warnings that only show up in certain situations.
